In [ ]:
# Importing the necessary modules
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [ ]:
# Loading the data frame in
original_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m12/lesson_3/datasets/garments-worker-productivity.csv')
original_df = original_df.drop(columns=['wip', 'day'])
original_df.dropna()

original_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   object
 1   quarter                1197 non-null   object
 2   department             1197 non-null   object
 3   team                   1197 non-null   int64
 4   targeted_productivity  1197 non-null   float64
 5   smv                    1197 non-null   float64
 6   over_time              1197 non-null   int64
 7   incentive              1197 non-null   int64
 8   idle_time              1197 non-null   float64
 9   idle_men               1197 non-null   int64
 10  no_of_style_change     1197 non-null   int64
 11  no_of_workers          1197 non-null   float64
 12  actual_productivity    1197 non-null   float64
dtypes: float64(5), int64(5), object(3)
memory usage: 121.7+ KB

In [ ]:
# Cleaning the data
X = original_df.drop(columns=['actual_productivity'])

X = pd.get_dummies(X, dtype='int',columns=['department', 'date', 'quarter', 'team'])

y = original_df['actual_productivity'].values.reshape(-1,1)

X

,targeted_productivity,smv,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,department_finishing,department_finishing,...,team_3,team_4,team_5,team_6,team_7,team_8,team_9,team_10,team_11,team_12
0,0.80,26.16,7080,98,0.0,0,0,59.0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0.75,3.94,960,0,0.0,0,0,8.0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0.80,11.41,3660,50,0.0,0,0,30.5,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0.80,11.41,3660,50,0.0,0,0,30.5,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0.80,25.90,1920,50,0.0,0,0,56.0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,0.75,2.90,960,0,0.0,0,0,8.0,1,0,...,0,0,0,0,0,0,0,1,0,0
1193,0.70,3.90,960,0,0.0,0,0,8.0,1,0,...,0,0,0,0,0,1,0,0,0,0
1194,0.65,3.90,960,0,0.0,0,0,8.0,1,0,...,0,0,0,0,1,0,0,0,0,0
1195,0.75,2.90,1800,0,0.0,0,0,15.0,1,0,...,0,0,0,0,0,0,1,0,0,0
1196,0.70,2.90,720,0,0.0,0,0,6.0,1,0,...,0,0,0,1,0,0,0,0,0,0

In [ ]:
# Splitting data set into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
# Loading linear regression
lr1 = LinearRegression()

lr1.fit(X_train, y_train)

lr1_train_score = lr1.score(X_test, y_test)

lr1_train_score

0.2507716125099647

In [ ]:
lr = sm.OLS(y_train, X_train).fit()

p_values = lr.pvalues.sort_values()

select_cols = p_values.loc[p_values < 0.05]

select_cols

targeted_productivity    8.183267e-29
department_finishing     8.317081e-11
smv                      4.725308e-10
team_1                   2.113860e-07
quarter_Quarter5         2.220945e-07
no_of_workers            2.976524e-07
idle_men                 1.394000e-06
team_3                   1.470448e-06
department_finishing     6.560982e-06
quarter_Quarter1         2.334018e-05
quarter_Quarter2         9.346617e-05
team_4                   1.279636e-04
date_1/31/2015           8.828820e-04
team_2                   1.684163e-03
quarter_Quarter4         2.254351e-03
team_12                  2.563234e-03
date_2/5/2015            1.100237e-02
date_1/22/2015           1.527013e-02
quarter_Quarter3         2.860082e-02
team_11                  4.391058e-02
idle_time                4.668183e-02
dtype: float64

In [ ]:
X[select_cols.index]
X = X[select_cols.index]

Checking if this data is attendable or just bad data. Looks like it just Bad data .